### ISSUE TITLE
Hello , Does this ane works with bluecats and kontakt.io beacons ?

### ISSUE THREAD

**Issue by ghost** [distriqt/airnativeextensions#334]
Hello , Does this ane works with bluecats and kontakt.io beacons ? is it still working and is it going to be updated when beacons get updates ?

**Comment by marchbold** [comment]
Hi,

All the ANEs here are deprecated. Please see our site https://airnativeextensions.com for access to the latest extensions.

The current Beacon ANE works with any beacon implementing Apple's iBeacon standard.

https://airnativeextensions.com/extension/com.distriqt.Beacon

Cheers
